---
title: Dance With Rust And Python 1 Packaging Rust with Python's pip
published: true
tag: 
 - Low-level Programming
 - Python  
 - Rust  
 - pip
 - FFI
---

# Packaging Rust With Python's Pip

Most of programmer, I believe, know rust partially for its intensive and reliable application in Web-Assembly. As a modern programming language, Rust builds the `FFI` between `JavaScript`	`Node` what empower the internet. the related packages `wasmbindgen`, `web_sys`, `js_sys` map the Rust's object and JavaScript's object, and bridge the interface. 
our topic also starts here, if we can build the interface with javascript, why do we transplant that into python or other programming languages? 
As a matter of fact, someone has already started and has been working on these. Maybe some of you heard the terminology `WASI` what is the exact tech stack they are working on. 

In this section, we will be setting up our pip package so that it can utilize Rust code.
This will enable us to use Python setup tools to import our Rust pip package, compile it for our system, and use it within our Python code.

## Project Setting Up

- initialize a rust library. 

Note that we gonna use it as a library, not a binary. 
`cargo new --lib demo` 

- Dependencies and Other Meta Data
```toml
[package]
name = "demo"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[lib]
name = "demo"
crate-type = ["cdylib"]
```
One more thing to note, It's necessary the specify the library type. Defining the crate-type variable as
cdylib tells the compiler that we want a dynamic system library to be
loaded by another language. If we do not put this in, we will not be able
to compile our code when installing our library via pip.

- Config file
we need to define the configuration in the .cargo/config file:
```config
[target.x86_64-apple-darwin]
rustflags = [
 "-C", "link-arg=-undefined",
 "-C", "link-arg=dynamic_lookup",
]
[target.aarch64-apple-darwin]
rustflags = [
 "-C", "link-arg=-undefined",
 "-C", "link-arg=dynamic_lookup",
]
```
This is the configuration for MacOS, you can remove it for Linux and Windows.

## Python Setting Up

- Create a `setup.py` file as the root of our module which will  import
all the requirements that we need.
How does `pip` know where the rust library is? Or rather, How can we tell the library `pip` will use?
, we can define our setup at the file. 
```python 
setup(
 name="demo",
 version="0.1",
 rust_extensions=[RustExtension(
 ".demo.demo",
 path="Cargo.toml", binding=Binding.PyO3)],
 packages=["demo"],
 classifiers=[
 "License :: OSI Approved :: MIT License",
 "Development Status :: 3 - Alpha",
 "Intended Audience :: Developers",
 "Programming Language :: Python",
 "Programming Language :: Rust",
 "Operating System :: POSIX",
 "Operating System :: MacOS :: MacOS X",
 ],
 zip_safe=False,
)
```
the `rust_extensions` parameter points the actual module that to be created in rust.
Alternatively, there is an easier way to do this without touch these tedious staff. But `setuptools_rust` must be installed.

```bash 
#!/usr/bin/env python
from setuptools import dist
dist.Distribution().fetch_build_eggs(['setuptools_rust'])
from setuptools import setup
from setuptools_rust import Binding, RustExtension
```

## Coding The Rust Library

```rust 
// src/lib.rs
use pyo3::prelude::*;
use pyo3::wrap_pyfunction;

#[pyfunction]
fn hello() {
	 println!("congratulation, it works");
}
#[pymodule]
fn demo(_py: Python, m: &PyModule) ->  PyResult<()> {
 m.add_wrapped(wrap_pyfunction!(hello));
 Ok(())
}
```
the `pyo3` serve as the `FFI` to Python, tell the compiler to map our rust code into "python code", you can take it as `wasmbindgen` in Web-Assembly.
the macros `#[pymodule]` will expand it python module after compilation in which methods `hello` will be availible as python method.


## Packaging And Test

Since it is a pip package we can install it with `pip`.
```python 
pip install <path-to-the-project>@main
```
in our python command line interface type,
```python 
from demo import hello 
hello()
```
it will print `congratulation, it works`.

Here we have it! Congratulations, you have done the first the magic of Rust and Pyhton, More are to go.
