---
title: minimal markdown blog CMS for static site
published: true
tag: 
 - markdown 
 - CMS 
 - minimal style 
 - static site
---

# Minimal markdown blog CMS for static site

Beforehand, you may ask what is [noer](https://github.com/HomelyGuy/noer), 

noer is a minimal, elegant and content-orientated static style blog CMS for those who prefer Markdown, static site, Web-Assembly. Markdown-based, simple to use; Static Style, github-pages supported, easy to deploy, serve and maintain; No JS/CSS/HTML touched; It makes content management Simple and Efficint.

Here we gonna customize `Noer`, and make our own static style blog site. 

## Pre-requisite

- As usual, rust tool-chain must be installed and put these tools in `PATH`
- Noer is built upon Web-Assembly and [yew](https://yew.rs),
	so you need to yew tool-chain installed 
	- `cargo install trunk`
	- `rustup target add wasm32-unknow-unknow`

## Configuration 
the file `src/constant.rs` contains the bare-bone infomation of the site, such as 
- `MODE` the current mode of the project, noer will set logger if in development mode and disable it is release mode.  
- `ITEMS_PER_PAGE` number of posts card that a page to display, note that it shall be multiple of 3.
- `ADMIN` username of the ower.
- `SITE_NAME` the name you want call the site.
- `LOGO_PIC`: the logo display in the page.
- `AVATR_PIC` avatar of the user
- `SITE_DESCRIPTION` extented html represented as website footer.
- `USER_INFO` some extra infomation of the user present to viewers, such as social network, email, etc. Note that it is line-separated, each line is a key-value pair.

you can change any of these fields to your satisfication.

## Compile
Since `nore` is static style website, the output of it must be compiled before we use.  
`subpath` support is enabled by specifying the `SUBPATH` in `constant.rs`,
so if you wanna compile for github Page, you should enable it. 
Once all is done, there is script that does favor for you,

```bash 
$ bash ./build.sh
```
it will compile and its output will locate in directory you specified.

## Deployment
- the normal way
Deploying noer as web application is just as simple as exposing the compiled `index.html`. here representing an example for nginx user
```
// /etc/nginx/sites-enabled/noer.conf
server {
	listen 8080;
	listen [::]:8080 ;

  root <absolute-path-to-project-directory>/<compiled-output-directory>;

	index index.html;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}
}

// Note that the example above is deployed to localhost:8080/
// if you prefer to deploying to sub path `localhost:8080/demo/`
// configue the `subpath` in `src/constant.rs`
// rename the compiled output directory to `demo`
server {
	...
  root <absolute-path-to-project-directory>;
	location /demo {
		...
	}
	...
}
```

- Github Pages
Just copy the all content of the directory to the root of the repository or its `docs/` subfold. It will work after a few seconds.
you can check my [tech blog](https://homelyguy.github.io/noer/) to preview and see around

## Writing a Blog
Here we gonna write our first blog. 
- name of a post
	there are some requirements you need aware of naming of a post, a valid name should be in the following format:
	`<timestamp>-<title>.rmd`
	where `timestamp` should consist of at least `year`(xxxx or xx), `month`(1-12), `day`(1-31), optional `hour`(0-23), optional `minite`(0-59), optional `second`(0-59). 
	there are some valid examples:
	`2022-10-01-test-title.rmd`
	`2022-10-01-23-test-title.rmd`
	`2022-10-01-23-00-test-title.rmd`
	`2022-03-test-title.rmd`(INVALID)
	`2022-10-01-23.rmd`(INVALID)

- meta data
	``` markdown 
		---
		title: test title
		published: true
		tag: 
		 - markdown 
		 - CMS 
		 - minimal style 
		 - static site
		---
	```
	inside the `---` block, you should have at least `title`, `tag`.

- register at `markdown.index`
	append the name of the post to the `markdown.index`
	refresh the home page then new post will show up

## Issues & Tips
I orginally created `noer` to repace the my old [CMS](https://github.com/homelyguy/mathematics), but post ajax is currently not supported in yew. 

not all markdown features are supported for the limitation of `pulldown-cmark`, you can go to post named `demo` to check. 

